#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=00:10:00
#PBS -N app-convert-tractmeasures-to-tractprofile
#PBS -l vmem=8gb

rm -f profiles

set -ex

time singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./convert_tractmeasures.py
